apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    tier: FrontEnd
    app: apache
spec:
  containers:
  - image: bitnami/apache:latest
    name: apache-container
    ports:
    - containerPort: 8080
      protocol: TCP