# 1. MySQL Secret YAML
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
  # type은 Opaque가 기본값
  # type: Opaque
  # 아래 값들은 base64 인코딩 필요
  # echo -n 'user1' | base64 -> dXNlcjE=
  # echo -n 'pw1234' | base64 -> cHcxMjM0
  # echo -n 'rootpw9876' | base64 -> cm9vdHB3OTg3Ng==
  # echo -n 'mydb' | base64 -> bXlkYg==
data:
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: cHcxMjM0
  MYSQL_ROOT_PASSWORD: cm9vdHB3OTg3Ng==
  MYSQL_DATABASE: bXlkYg==